// src/adapters/vue/components/GridStack.vue
<template>
  <div ref="gridRef" class="grid-stack ldesign-grid-vue">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, provide, onMounted, onUnmounted, watch } from 'vue'
import { GridManager } from '../../../core/GridManager'
import type { IGridInstance } from '../../../types'
import type { GridStackProps, GridStackEmits } from '../types'

const props = withDefaults(defineProps<GridStackProps>(), {
  options: () => ({})
})

const emit = defineEmits<GridStackEmits>()

const gridRef = ref<HTMLElement>()
const gridInstance = ref<IGridInstance>()

// Provide grid instance for child components (must be at setup top level)
provide('grid-instance', gridInstance)

onMounted(() => {
  if (!gridRef.value) return

  const manager = GridManager.getInstance()
  gridInstance.value = manager.create(gridRef.value, props.options)

  // Setup event listeners
  gridInstance.value.on('added', (item) => {
    emit('added', item)
  })

  gridInstance.value.on('removed', (item) => {
    emit('removed', item)
  })

  gridInstance.value.on('change', (items) => {
    emit('change', items)
    emit('update:modelValue', items)
  })

  gridInstance.value.on('dragstart', (item) => {
    emit('dragstart', item)
  })

  gridInstance.value.on('dragstop', (item) => {
    emit('dragstop', item)
  })

  gridInstance.value.on('resizestart', (item) => {
    emit('resizestart', item)
  })

  gridInstance.value.on('resizestop', (item) => {
    emit('resizestop', item)
  })

  gridInstance.value.on('dropped', (item, data) => {
    emit('dropped', data)
  })
})

onUnmounted(() => {
  if (gridInstance.value) {
    gridInstance.value.destroy()
  }
})

// Watch for modelValue changes
watch(() => props.modelValue, (newValue) => {
  if (!newValue || !gridInstance.value) return
  
  // Load layout from modelValue
  gridInstance.value.load({
    items: newValue
  })
}, { deep: true })

// Expose methods for template refs
defineExpose({
  gridInstance,
  addItem: (element: HTMLElement, options: any) => gridInstance.value?.addItem(element, options),
  removeItem: (id: string) => gridInstance.value?.removeItem(id),
  clear: () => gridInstance.value?.clear(),
  save: () => gridInstance.value?.save(),
  load: (layout: any) => gridInstance.value?.load(layout)
})
</script>

<style>
.ldesign-grid-vue {
  width: 100%;
  height: 100%;
}
</style>

// src/adapters/react/components/GridStack.tsx
/**
 * React GridStack component
 */

import React, { useRef, useEffect, useState, useImperativeHandle, forwardRef } from 'react'
import { GridManager } from '../../../core/GridManager'
import type { IGridInstance } from '../../../types'
import type { GridStackProps } from '../types'
import { GridProvider } from '../context/GridContext'

export interface GridStackRef {
  gridInstance: IGridInstance | null
  addItem: (element: HTMLElement, options: any) => void
  removeItem: (id: string) => void
  clear: () => void
  save: () => any
  load: (layout: any) => void
}

export const GridStack = forwardRef<GridStackRef, GridStackProps>((props, ref) => {
  const {
    options = {},
    children,
    onChange,
    onAdded,
    onRemoved,
    onDragStart,
    onDragStop,
    onResizeStart,
    onResizeStop,
    onDropped,
    className = '',
    style
  } = props

  const gridRef = useRef<HTMLDivElement>(null)
  const [gridInstance, setGridInstance] = useState<IGridInstance | null>(null)

  useEffect(() => {
    if (!gridRef.current) return

    const manager = GridManager.getInstance()
    const instance = manager.create(gridRef.current, options)

    // Setup event listeners
    if (onChange) {
      instance.on('change', onChange)
    }

    if (onAdded) {
      instance.on('added', onAdded)
    }

    if (onRemoved) {
      instance.on('removed', onRemoved)
    }

    if (onDragStart) {
      instance.on('dragstart', onDragStart)
    }

    if (onDragStop) {
      instance.on('dragstop', onDragStop)
    }

    if (onResizeStart) {
      instance.on('resizestart', onResizeStart)
    }

    if (onResizeStop) {
      instance.on('resizestop', onResizeStop)
    }

    if (onDropped) {
      instance.on('dropped', onDropped)
    }

    setGridInstance(instance)

    return () => {
      instance.destroy()
    }
  }, []) // Only run on mount

  // Expose methods via ref
  useImperativeHandle(ref, () => ({
    gridInstance,
    addItem: (element: HTMLElement, itemOptions: any) => {
      if (gridInstance) {
        gridInstance.addItem(element, itemOptions)
      }
    },
    removeItem: (id: string) => {
      if (gridInstance) {
        gridInstance.removeItem(id)
      }
    },
    clear: () => {
      if (gridInstance) {
        gridInstance.clear()
      }
    },
    save: () => {
      return gridInstance?.save()
    },
    load: (layout: any) => {
      if (gridInstance) {
        gridInstance.load(layout)
      }
    }
  }))

  return (
    <GridProvider gridInstance={gridInstance}>
      <div
        ref={gridRef}
        className={`grid-stack ldesign-grid-react ${className}`}
        style={style}
      >
        {children}
      </div>
    </GridProvider>
  )
})

GridStack.displayName = 'GridStack'

export default GridStack
